name: diablo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  alarmplayer: ^1.1.1
  flutter:
    sdk: flutter
  flutter_background_service: any
  flutter_background_service_android: "6.0.1"
  flutter_local_notifications: ^17.2.1+2
  http: ^1.2.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sound.mp3

